# action.yml
name: 'FireClover Reporter'
description: 'FireClover Vulnerability Management Reporter Tool'
branding:
  icon: 'align-left'  
  color: 'orange'
inputs:
  instance-url:
    description: 'The FireClover reporter instance url'
    required: true
    default: ''
  email:
    description: 'The email address to which the report will be sent.'
    required: false
    default: '' 
  result-file:  
    description: 'The path to the result file'
    required: true
    default: ''
  workspace:  
    description: 'The workspace to upload the result to'
    required: true
    default: ''
  username:  
    description: 'The username to login to the reporter tool'
    required: false
    default: 'faraday'
  password:  
    description: 'The password to login to the reporter tool'
    required: true
    default: ''
  quiet:  
    description: 'Verbosity of the tool output'
    required: false
    default: true
  ignore-info-severity:  
    description: 'Ignore information severity vulnerabilities of the tool output'
    required: false
    default: true
  allow-style:  
    description: 'Verbosity style of the tool output (valid values:Always, Never, Terminal)'
    required: false
    default: ''
 
runs:
  using: "composite"
  steps:
    - name: Setup Reporter
      run: |  
        pip install faraday-cli -q
        faraday-cli auth -f "${{ inputs.instance-url }}" -i -u "${{ inputs.username }}" -p "${{ inputs.password }}"
        faraday-cli workspace select "${{ inputs.workspace }}" || faraday-cli workspace create "${{ inputs.workspace }}" 
      shell: bash
    - if: !inputs.ignore-info-severity || !inputs.quiet
      run: |  
        faraday-cli set quiet ${{ inputs.quiet }}
        faraday-cli set allow_style ${{ inputs.allow-style }}
        faraday-cli set ignore_info_severity ${{ inputs.ignore-info-severity }}
      shell: bash
    - name:  Upload Results
      run:   faraday-cli tool report "${{ inputs.result-file }}" 
      shell: bash
